export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const CREATE_POST_LIKE_REQUEST = 'CREATE_POST_LIKE_REQUEST';
export const CREATE_POST_LIKE_SUCCESS = 'CREATE_POST_LIKE_SUCCESS';
export const CREATE_POST_LIKE_ERROR = 'CREATE_POST_LIKE_ERROR';
